### ISSUE TITLE
Can't get the plugin to work. Customer number "Kundennummer" is a required field but it's not autofilled

### ISSUE THREAD

**Issue by MMilesMM** [wiomoc/pretix-sumup-payment#1]
Hi, like I stated in the title, I can't configure the plugin. After I insert the API Token and try to save/activate the payment method it gives me an error about a required field I need to fill in: customer number or in German: Kundennummer but it's greyed out.

Current installation:
pretix version: 2024.4.0 in docker 25.0.3, build 4debf41
The plugin is installed via the custom docker container method.

**Comment by wiomoc** [comment]
Hi Miles,
thanks for the report. I fixed this issue in 88c0b04. The merchant code should not be settable by the user, it is only there as informal note

**Comment by MMilesMM** [comment]
Thanks for the fix. But in pip (PyPi) it still has the old version, soI can't get it to (easily) work with a Docker setup.

**Comment by wiomoc** [comment]
Thanks for remainding me! I just published it as [1.1.4](https://pypi.org/project/pretix-sumup-payment/1.1.4/)
